{% set name = "evidently" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 03d08d01da52facd07db6cf4a2b2bb776d2f4e5009b4fd0d8805614286635bbe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - evidently=evidently.cli:app

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dataclasses >=0.6
    - fastapi >=0.98.0
    - fastapi_utils >=0.2.1
    - iterative-telemetry >=0.0.5
    - nltk >=3.6.7
    - numpy >=1.19.5
    - pandas >=1.3.5
    - plotly >=5.5.0
    - pydantic >=1.10,<2
    - pyarrow >=11
    - python >=3.7
    - pyyaml >=5.1
    - requests >=2.19.0
    - rich >=13
    - scikit-learn >=0.24.0
    - scipy >=1.5.4
    - statsmodels >=0.12.2
    - typer >=0.9
    - uvicorn >=0.22.0
    - watchdog >=3

test:
  imports:
    - evidently
  commands:
    - pip check
    - evidently --help
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
