{% set name = "evidently" %}
{% set version = "0.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evidently-{{ version }}.tar.gz
  sha256: 182f52e9d67d4ebfb42b1642318be667786b7c1906c1dc84e1940e2c829a5525

build:
  entry_points:
    - evidently=evidently.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - plotly >=5.5.0
    - statsmodels >=0.12.2
    - scikit-learn >=0.24.0
    - pandas >=1.3.5
    - numpy >=1.19.5
    - nltk >=3.6.7
    - scipy >=1.5.4
    - requests >=2.21.0
    - pyyaml >=5.1
    - pydantic <2
    - fastapi >=0.100.0
    - fastapi-restful >=0.5.0
    - typing_inspect >=0.9.0
    - uvicorn >=0.22.0
    - watchdog >=3
    - typer >=0.3
    - rich >=13
    - iterative-telemetry >=0.0.5
    - fsspec
# from https://github.com/pandas-dev/pandas/blob/main/pyproject.toml
# parquet = ['pyarrow>=10.0.1']
    - pyarrow >=10.0.1

test:
  imports:
    - evidently
  commands:
    - pip check
    - evidently --help
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
