{% set name = "evidently" %}
{% set version = "0.4.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evidently-{{ version }}.tar.gz
  sha256: 97564f8b78eda14b4daa611698dba7c0cbcdf22708a479d8d1cc28d4c91ba9b1

build:
  entry_points:
    - evidently=evidently.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - plotly >=5.10.0
    - statsmodels >=0.12.2
    - scikit-learn >=1.0.1
    - pandas >=1.3.5
    - numpy >=1.22.0
    - nltk >=3.6.7
    - scipy >=1.10.0
    - requests >=2.32.0
    - pyyaml >=5.4
    - pydantic >=1.10.13
    - litestar >=2.8.3
    - typing_inspect >=0.9.0
    - uvicorn-standard >=0.22.0
    - watchdog >=3.0.0
    - typer >=0.3
    - rich >=13
    - iterative-telemetry >=0.0.5
    - dynaconf >=3.2.4
    - certifi >=2024.07.4
    - urllib3 >=1.26.19
    - fsspec >=2024.2.0
    - ujson >=5.4.0
    - opentelemetry-api >=1.25.0
    - opentelemetry-sdk >=1.25.0
    - opentelemetry-proto >=1.25.0
    - opentelemetry-exporter-otlp-proto-grpc >=1.25.0
    - opentelemetry-exporter-otlp-proto-http >=1.25.0
# from https://github.com/pandas-dev/pandas/blob/main/pyproject.toml
# parquet = ['pyarrow>=10.0.1']
    - pyarrow >=10.0.1

test:
  imports:
    - evidently
  commands:
    - pip check
    - evidently --help
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
