{% set name = "evidently" %}
{% set version = "0.4.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/evidentlyai/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4a8036ff48736cc832348ef491a33f4352971d5e146c5ccdee65577ca7f264f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - evidently=evidently.cli:app

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - plotly >=5.5.0
    - statsmodels >=0.12.2
    - scikit-learn >=0.24.0
    - pandas >=1.3.5
    - numpy >=1.19.5
    - nltk >=3.6.7
    - scipy >=1.5.4
    - requests >=2.21.0
    - pyyaml >=5.1
    - pydantic <2
    - fastapi >=0.100.0
    - fastapi-restful >=0.5.0
    - typing_inspect >=0.9.0
    - uvicorn >=0.22.0
    - watchdog >=3
    - typer >=0.3
    - rich >=13
    - iterative-telemetry >=0.0.5
    - pyarrow <11.0dev

test:
  imports:
    - evidently
  commands:
    - pip check
    - evidently --help
  requires:
    - pip

about:
  home: https://github.com/evidentlyai/evidently
  doc_url: https://docs.evidentlyai.com/
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
