schema_version: 1

context:
  name: evidently
  version: "0.7.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/evidently-${{ version }}.tar.gz
  sha256: e27a9591d7cb8514bf64bfde35a7227ad9f216f3c091d602fe209a7d03779ff5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - evidently=evidently.legacy.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - plotly >=5.10.0,<6
    - statsmodels >=0.12.2
    - scikit-learn >=1.0.1
    - pandas >=1.3.5
    - numpy >=1.22.0
    - nltk >=3.6.7
    - scipy >=1.10.0
    - requests >=2.32.0
    - pyyaml >=5.4
    - pydantic >=1.10.16
    - litestar >=2.8.3
    - typing_inspect >=0.9.0
    - uvicorn-standard >=0.22.0
    - watchdog >=3.0.0
    - typer >=0.3
    - rich >=13
    - iterative-telemetry >=0.0.5
    - dynaconf >=3.2.4
    - certifi >=2024.7.4
    - urllib3 >=1.26.19
    - fsspec >=2024.6.1
    - ujson >=5.4.0
    - deprecation >=2.1.0
    - cryptography >=43.0.1
    - uuid6 >=2024.7.10
    # from https://github.com/pandas-dev/pandas/blob/main/pyproject.toml
    # for pandas-parquet we need pyarrow>=10.0.1
    - pyarrow >=10.0.1

tests:
  - python:
      imports:
        - evidently
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - evidently --help

about:
  summary: Analyze, monitor, and debug machine learning model in production.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/evidentlyai/evidently
  documentation: https://docs.evidentlyai.com/

extra:
  recipe-maintainers:
    - thewchan
